# Generated by Django 4.0.4 on 2022-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(max_length=3, verbose_name='Возраст'),
        ),
    ]
