# Generated by Django 3.2 on 2021-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время написания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки'),
        ),
    ]
