# Generated by Django 3.2 on 2021-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Аватар'),
        ),
    ]
