# Generated by Django 3.2 on 2021-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0002_auto_20210730_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.SmallIntegerField(choices=[('1', 'Плохо'), ('2', 'Нормально'), ('3', 'Хорошо'), ('4', 'Легендарно')], default=1),
            preserve_default=False,
        ),
    ]
