# Generated by Django 3.2 on 2021-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0003_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[('1', 'Плохо'), ('2', 'Нормально'), ('3', 'Хорошо'), ('4', 'Легендарно')], max_length=10),
        ),
    ]
