# Generated by Django 3.2 on 2021-08-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0004_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[(1, 'Плохо'), (2, 'Нормально'), (3, 'Хорошо'), (4, 'Легендарно')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', related_query_name='target', to='photoload.post', verbose_name='Пост'),
        ),
    ]
