# Generated by Django 4.0.4 on 2022-06-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0004_alter_post_rating_alter_user_age_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='target',
            new_name='target_post',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='value',
        ),
    ]
