# Generated by Django 3.2 on 2021-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0005_auto_20210801_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.SmallIntegerField(choices=[(1, 'Плохо'), (2, 'Нормально'), (3, 'Хорошо'), (4, 'Легендарно')], default='2', max_length=10),
        ),
    ]
