# Generated by Django 4.0.4 on 2022-06-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0005_rename_target_rate_target_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='photoload.post', verbose_name='Пост'),
        ),
    ]
