# Generated by Django 3.2 on 2021-08-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0007_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_comment', to='photoload.comment', verbose_name='Комментарий'),
        ),
    ]
