# Generated by Django 3.2 on 2021-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoload', '0008_alter_comment_target_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
